### ISSUE TITLE
Materiales para posteos en RRSS

### ISSUE THREAD

**Issue by danielcarranza** [datauy/UruguayLeaks#21]
From plantilla created by [danielcarranza](https://github.com/danielcarranza): datauy/plantilla#26  

Usar plantilla gráfica: https://drive.google.com/open?id=1FMd516v5CyM6cCW4CFw6IxhtSjWdabW0

- [ ] Tres imágenes difrentes (#24)
- [ ] Posteos para lanzamiento en base a metadescripción (#10) y usando palabras clave definidas (#4)
- [ ] Enlazar al sitio
- [ ] Etiquetar a aliados
- [ ] Publicar artículo de lanzamiento del blog (#27)
